#!/usr/bin/env python3
"""Audit whether HMDA Book 1 is durably reproducible from the repository.

The canonical Book 1 source is a source graph, not a historical local PDF:
Cases 01-05 base + Cases 06-16 + Cases 17-30, assembled deterministically by
scripts/build_book1_master.py. Spatial truth is separately locked by the final
Shigai selection manifest and room skin.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import sys
import yaml

ROOT = Path(__file__).resolve().parents[1]
EXPECTED_30 = list(range(1, 31))
EXPECTED_PHASE2 = list(range(6, 17))
EXPECTED_PHASE3 = list(range(17, 31))
SELECTED_15 = [
    "HMDA_02", "HMDA_04", "HMDA_06", "HMDA_07", "HMDA_10",
    "HMDA_12", "HMDA_13", "HMDA_15", "HMDA_17", "HMDA_19",
    "HMDA_20", "HMDA_22", "HMDA_23", "HMDA_25", "HMDA_29",
]


def load_path(path: Path):
    if not path.exists():
        raise SystemExit(f"MISSING: {path}")
    return yaml.safe_load(path.read_text(encoding="utf-8"))


def load(rel: str):
    return load_path(ROOT / rel)


def mission_numbers(doc) -> list[int]:
    return [int(m["number"]) for m in (doc or {}).get("missions", []) if "number" in m]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--master",
        type=Path,
        default=None,
        help="Optional assembled canonical master generated by build_book1_master.py.",
    )
    ap.add_argument(
        "--require-canonical-30",
        action="store_true",
        help="Fail unless --master exists and contains exactly Cases 01-30.",
    )
    args = ap.parse_args()

    production = load("content/book1_en_production.yml")
    blueprint = load("content/book_en.yml")
    phase2 = load("content/book1_en_phase2.yml")
    phase3 = load("content/book1_en_phase3.yml")
    spatial = load("content/spatial_source_manifest_final.yml")
    skin = load("content/spatial_room_skin.yml")

    prod_nums = mission_numbers(production)
    blueprint_nums = mission_numbers(blueprint)
    phase2_nums = mission_numbers(phase2)
    phase3_nums = mission_numbers(phase3)
    spatial_cases = [str(c.get("id")) for c in spatial.get("cases", [])]
    skin_cases = list((skin.get("cases") or {}).keys())
    meta = str(spatial.get("meta_engine", {}).get("message", "")).replace(" ", "")

    master_nums = None
    if args.master is not None:
        master = load_path(args.master.resolve())
        master_nums = mission_numbers(master)

    print("HMDA BOOK 1 LAUNCH AUDIT")
    print(f"base renderer missions:            {len(prod_nums)} -> {prod_nums}")
    print(f"phase-2 production missions:       {len(phase2_nums)} -> {phase2_nums}")
    print(f"phase-3 production missions:       {len(phase3_nums)} -> {phase3_nums}")
    print(f"story blueprint missions:          {len(blueprint_nums)}")
    if master_nums is not None:
        print(f"assembled canonical master:        {len(master_nums)} missions")
    else:
        print("assembled canonical master:        not supplied to audit")
    print(f"locked spatial sources:            {len(spatial_cases)}")
    print(f"room skins:                        {len(skin_cases)}")
    print(f"locked meta message:               {meta}")

    errors: list[str] = []
    warnings: list[str] = []

    if prod_nums != [1, 2, 3, 4, 5]:
        errors.append("book1_en_production.yml must remain the Cases 01-05 base tranche.")
    if phase2_nums != EXPECTED_PHASE2:
        errors.append("book1_en_phase2.yml must contain exactly Cases 06-16.")
    if phase3_nums != EXPECTED_PHASE3:
        errors.append("book1_en_phase3.yml must contain exactly Cases 17-30.")
    if blueprint_nums != EXPECTED_30:
        errors.append("book_en.yml is not a complete ordered 01-30 story blueprint.")
    if spatial_cases != SELECTED_15:
        errors.append("final spatial manifest does not match the locked 15-case production bank.")
    if set(skin_cases) != set(SELECTED_15):
        errors.append("spatial_room_skin.yml does not cover exactly the locked 15 production modules.")
    if meta != "CHECKTHEOLDMAP":
        errors.append("final spatial manifest meta message is not CHECKTHEOLDMAP.")

    if master_nums is not None and master_nums != EXPECTED_30:
        errors.append("assembled canonical master is not exactly Cases 01-30.")
    if master_nums is None:
        warnings.append(
            "No assembled master was supplied. Source tranches can still be audited, "
            "but CI should build and audit the canonical master before rendering."
        )

    print()
    for item in warnings:
        print(f"WARNING: {item}")
    for item in errors:
        print(f"ERROR: {item}")

    if errors:
        print("\nRESULT: FAIL")
        return 2
    if args.require_canonical_30 and master_nums != EXPECTED_30:
        print("\nRESULT: BLOCKED - canonical assembled 30-mission master not verified")
        return 3

    print("\nRESULT: PASS WITH WARNING" if warnings else "\nRESULT: PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
